name: PX4 Firmware Buildv2

on:
  workflow_dispatch:   # jen ruční spuštění přes Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PX4 Firmware
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git python3-pip python3-venv python3-dev build-essential \
          ninja-build cmake genromfs ccache gawk zip curl wget
          pip3 install --user pyserial empy toml numpy pandas jinja2 pyulog
      - name: Install PX4 toolchain
        run: |
          bash ./Tools/setup/ubuntu.sh
      - name: Build PX4 firmware
        run: |
          make px4_fmu-v5_default
      - name: Upload PX4 artifact
        uses: actions/upload-artifact@v4
        with:
          name: px4_fmu-v5_default
          path: build/px4_fmu-v5_default/px4_fmu-v5_default.px4
